// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddJavaByDialog() {
  return window['go']['main']['App']['AddJavaByDialog']();
}

export function GetActiveServer() {
  return window['go']['main']['App']['GetActiveServer']();
}

export function GetJvmPid() {
  return window['go']['main']['App']['GetJvmPid']();
}

export function GetMaxPlayers() {
  return window['go']['main']['App']['GetMaxPlayers']();
}

export function GetOnlinePlayers() {
  return window['go']['main']['App']['GetOnlinePlayers']();
}

export function GetPlayerList() {
  return window['go']['main']['App']['GetPlayerList']();
}

export function GetServerJava(arg1) {
  return window['go']['main']['App']['GetServerJava'](arg1);
}

export function GetServerList() {
  return window['go']['main']['App']['GetServerList']();
}

export function GetServerMemory(arg1) {
  return window['go']['main']['App']['GetServerMemory'](arg1);
}

export function GetServerModCount(arg1) {
  return window['go']['main']['App']['GetServerModCount'](arg1);
}

export function GetServerPluginCount(arg1) {
  return window['go']['main']['App']['GetServerPluginCount'](arg1);
}

export function GetServerProperties(arg1) {
  return window['go']['main']['App']['GetServerProperties'](arg1);
}

export function GetServerType(arg1) {
  return window['go']['main']['App']['GetServerType'](arg1);
}

export function GetServerUptime() {
  return window['go']['main']['App']['GetServerUptime']();
}

export function GetServerVersion(arg1) {
  return window['go']['main']['App']['GetServerVersion'](arg1);
}

export function SaveLogToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveLogToFile'](arg1, arg2);
}

export function ScanJavaList() {
  return window['go']['main']['App']['ScanJavaList']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function SetActiveServer(arg1) {
  return window['go']['main']['App']['SetActiveServer'](arg1);
}

export function SetServerJava(arg1, arg2) {
  return window['go']['main']['App']['SetServerJava'](arg1, arg2);
}

export function SetServerMemory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetServerMemory'](arg1, arg2, arg3);
}

export function SetServerProperties(arg1, arg2) {
  return window['go']['main']['App']['SetServerProperties'](arg1, arg2);
}

export function ShutdownAll() {
  return window['go']['main']['App']['ShutdownAll']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
