// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddJavaByDialog() {
  return window['go']['main']['App']['AddJavaByDialog']();
}

export function ConfirmSendVersion(arg1) {
  return window['go']['main']['App']['ConfirmSendVersion'](arg1);
}

export function GetActiveServer() {
  return window['go']['main']['App']['GetActiveServer']();
}

export function GetJavaList() {
  return window['go']['main']['App']['GetJavaList']();
}

export function GetServerJava(arg1) {
  return window['go']['main']['App']['GetServerJava'](arg1);
}

export function GetServerList() {
  return window['go']['main']['App']['GetServerList']();
}

export function GetServerMemory(arg1) {
  return window['go']['main']['App']['GetServerMemory'](arg1);
}

export function GetServerModCount(arg1) {
  return window['go']['main']['App']['GetServerModCount'](arg1);
}

export function GetServerPluginCount(arg1) {
  return window['go']['main']['App']['GetServerPluginCount'](arg1);
}

export function GetServerType(arg1) {
  return window['go']['main']['App']['GetServerType'](arg1);
}

export function GetServerUptime() {
  return window['go']['main']['App']['GetServerUptime']();
}

export function GetServerVersion(arg1) {
  return window['go']['main']['App']['GetServerVersion'](arg1);
}

export function SaveJavaList(arg1) {
  return window['go']['main']['App']['SaveJavaList'](arg1);
}

export function ScanJavaList() {
  return window['go']['main']['App']['ScanJavaList']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function SetActiveServer(arg1) {
  return window['go']['main']['App']['SetActiveServer'](arg1);
}

export function SetServerJava(arg1, arg2) {
  return window['go']['main']['App']['SetServerJava'](arg1, arg2);
}

export function SetServerMemory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetServerMemory'](arg1, arg2, arg3);
}

export function ShutdownAll() {
  return window['go']['main']['App']['ShutdownAll']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
