// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function AddJavaByDialog():Promise<model.JavaInfo>;

export function GetActiveServer():Promise<string>;

export function GetJvmPid():Promise<number>;

export function GetMaxPlayers():Promise<number>;

export function GetOnlinePlayers():Promise<number>;

export function GetPlayerList():Promise<Array<string>>;

export function GetServerJava(arg1:string):Promise<model.JavaInfo>;

export function GetServerList():Promise<model.ServerListResult>;

export function GetServerMemory(arg1:string):Promise<number|number>;

export function GetServerModCount(arg1:string):Promise<number>;

export function GetServerPluginCount(arg1:string):Promise<number>;

export function GetServerProperties(arg1:string):Promise<Record<string, string>>;

export function GetServerType(arg1:string):Promise<string>;

export function GetServerUptime():Promise<number>;

export function GetServerVersion(arg1:string):Promise<string>;

export function SaveLogToFile(arg1:string,arg2:string):Promise<string>;

export function ScanJavaList():Promise<Array<model.JavaInfo>>;

export function SendCommand(arg1:string):Promise<void>;

export function SetActiveServer(arg1:string):Promise<void>;

export function SetServerJava(arg1:string,arg2:string):Promise<void>;

export function SetServerMemory(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetServerProperties(arg1:string,arg2:Record<string, string>):Promise<void>;

export function ShutdownAll():Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopServer():Promise<void>;
